const products = {
  data: [
    {
      id: Date.now(),
      newItem: "NEW",
      name: "글레이즈 플럼퍼 글로스 4g",
      desc: "#은하수광택 #플럼퍼",
      price: 13000,
      category: "lip",
      img: "./page01_img/glaze_plump_gloss_01-430x430.jpg",
      imgHover: "./page01_img/glaze_plump_gloss_04-430x430.jpg",
    },
    {
      id: Date.now() + 1,
      newItem: "NEW",
      name: "MBTeye",
      desc: "#은하수광택 #플럼퍼",
      price: 30000,
      category: "eye",
      img: "./page01_img/MBTeye_01-430x430.jpg",
      imgHover: "./page01_img/MBTeye_04-430x430.jpg",
    },
    {
      id: Date.now() + 2,
      newItem: "NEW",
      name: "panda",
      desc: "#은하수광택 #플럼퍼",
      price: 7500,
      category: "cream",
      img: "./page01_img/missingU_panda_01-430x430.jpg",
      imgHover: "./page01_img/missingU_panda_02-430x430.jpg",
    },
    {
      id: Date.now() + 3,
      newItem: "NEW",
      name: "Tint",
      desc: "#은하수광택 #플럼퍼",
      price: 11000,
      category: "lip",
      img: "./page01_img/Dear_Darling_Oil_Tint_01-430x430.jpg",
      imgHover: "./page01_img/Dear_Darling_Oil_Tint_M_02-430x430.jpg",
    },
    {
      id: Date.now() + 4,
      newItem: "NEW",
      name: "Tint",
      desc: "#은하수광택 #플럼퍼",
      price: 11000,
      category: "lip",
      img: "./page01_img/Dear_Darling_Oil_Tint_01-430x430.jpg",
      imgHover: "./page01_img/Dear_Darling_Oil_Tint_M_02-430x430.jpg",
    },
    {
      id: Date.now() + 5,
      newItem: "NEW",
      name: "Tint",
      desc: "#은하수광택 #플럼퍼",
      price: 11000,
      category: "lip",
      img: "./page01_img/Dear_Darling_Oil_Tint_01-430x430.jpg",
      imgHover: "./page01_img/Dear_Darling_Oil_Tint_M_02-430x430.jpg",
    },
    {
      id: Date.now() + 6,
      newItem: "NEW",
      name: "Tint",
      desc: "#은하수광택 #플럼퍼",
      price: 11000,
      category: "lip",
      img: "./page01_img/Dear_Darling_Oil_Tint_01-430x430.jpg",
      imgHover: "./page01_img/Dear_Darling_Oil_Tint_M_02-430x430.jpg",
    },
    {
      id: Date.now() + 7,
      newItem: "NEW",
      name: "Tint",
      desc: "#은하수광택 #플럼퍼",
      price: 11000,
      category: "lip",
      img: "./page01_img/Dear_Darling_Oil_Tint_01-430x430.jpg",
      imgHover: "./page01_img/Dear_Darling_Oil_Tint_M_02-430x430.jpg",
    },
  ],
};

export default products;
